[target.x86_64-unknown-linux-gnu]
pre-build = ['./install_deps.sh']

[target.i686-unknown-linux-gnu]
pre-build = ['./install_deps.sh']

[target.aarch64-unknown-linux-gnu]
pre-build = ['./install_deps.sh']
