name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          rust: stable
        - os: ubuntu-latest
          rust: stable
        - os: ubuntu-latest
          rust: stable
        - os: ubuntu-latest
          rust: nightly
        - os: ubuntu-latest
          rust: nightly
        - os: ubuntu-latest
          rust: nightly
        - os: ubuntu-latest
          rust: beta
        - os: ubuntu-latest
          rust: beta
        - os: ubuntu-latest
          rust: beta

        - os: macos-latest
          rust: stable
        - os: macos-latest
          rust: nightly
        - os: macos-latest
          rust: beta

        - os: windows-latest
          rust: stable
        - os: windows-latest
          rust: stable
        - os: windows-latest
          rust: nightly
        - os: windows-latest
          rust: nightly
        - os: windows-latest
          rust: beta
        - os: windows-latest
          rust: beta
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Install ${{ matrix.rust }} rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        components: clippy
        override: true

    - name: Debug build
      run: cargo build --all-features -vv

    - name: Release build
      run: cargo build --release --all-features -vv

    - name: Clippy
      run: cargo clippy --all-features -vv -- -D warnings

    - name: Clippy tests
      run: cargo clippy --all-features -vv --tests -- -D warnings

    - name: Clippy release
      run: cargo clippy --all-features -vv --release -- -D warnings

    - name: Test
      run: cargo test --all-features -vv

  check-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install stable rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt
        override: true

    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -v -- --check

  publish-docs:
    runs-on: ubuntu-latest
    needs: [build, check-format]
    steps:
    - uses: actions/checkout@v2

    - name: Install stable rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Generate docs
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --no-deps --document-private-items

    - name: Publish the docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/doc
